# Form implementation generated from reading ui file 'D:\PythonProjects\AudioPlayer\src\client\interface.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(318, 347)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"color: #000;\n"
"border: none;\n"
"}\n"
"\n"
"#toolWidget{\n"
"background-color: #302c34;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"#listWidget{\n"
"background-color: #302c34;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"#backgroundWidget{\n"
"background-color: #454049;\n"
"}\n"
"\n"
"#headWidget{\n"
"background-color: #302c34;\n"
"border-radius: 5px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.backgroundWidget.setGeometry(QtCore.QRect(-1, -1, 351, 351))
        self.backgroundWidget.setObjectName("backgroundWidget")
        self.toolWidget = QtWidgets.QWidget(parent=self.backgroundWidget)
        self.toolWidget.setGeometry(QtCore.QRect(19, 299, 281, 41))
        self.toolWidget.setObjectName("toolWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backMusicButton = QtWidgets.QPushButton(parent=self.toolWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\PythonProjects\\AudioPlayer\\src\\client\\icons\\white\\arrow-left-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backMusicButton.setIcon(icon)
        self.backMusicButton.setIconSize(QtCore.QSize(22, 22))
        self.backMusicButton.setFlat(True)
        self.backMusicButton.setObjectName("backMusicButton")
        self.horizontalLayout.addWidget(self.backMusicButton)
        self.playMusicButton = QtWidgets.QPushButton(parent=self.toolWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\PythonProjects\\AudioPlayer\\src\\client\\icons\\white\\play-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.playMusicButton.setIcon(icon1)
        self.playMusicButton.setIconSize(QtCore.QSize(24, 24))
        self.playMusicButton.setObjectName("playMusicButton")
        self.horizontalLayout.addWidget(self.playMusicButton)
        self.nextMusicButton = QtWidgets.QPushButton(parent=self.toolWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\PythonProjects\\AudioPlayer\\src\\client\\icons\\white\\arrow-right-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.nextMusicButton.setIcon(icon2)
        self.nextMusicButton.setIconSize(QtCore.QSize(22, 22))
        self.nextMusicButton.setFlat(True)
        self.nextMusicButton.setObjectName("nextMusicButton")
        self.horizontalLayout.addWidget(self.nextMusicButton)
        self.shuffleButton = QtWidgets.QPushButton(parent=self.toolWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\PythonProjects\\AudioPlayer\\src\\client\\icons\\white\\shuffle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.shuffleButton.setIcon(icon3)
        self.shuffleButton.setIconSize(QtCore.QSize(20, 20))
        self.shuffleButton.setFlat(True)
        self.shuffleButton.setObjectName("shuffleButton")
        self.horizontalLayout.addWidget(self.shuffleButton)
        self.folderButton = QtWidgets.QPushButton(parent=self.toolWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\PythonProjects\\AudioPlayer\\src\\client\\icons\\white\\folder.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.folderButton.setIcon(icon4)
        self.folderButton.setIconSize(QtCore.QSize(20, 20))
        self.folderButton.setFlat(True)
        self.folderButton.setObjectName("folderButton")
        self.horizontalLayout.addWidget(self.folderButton)
        self.listWidget = QtWidgets.QListWidget(parent=self.backgroundWidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 40, 281, 251))
        self.listWidget.setObjectName("listWidget")
        self.headWidget = QtWidgets.QWidget(parent=self.backgroundWidget)
        self.headWidget.setGeometry(QtCore.QRect(-1, 0, 321, 34))
        self.headWidget.setObjectName("headWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headWidget)
        self.horizontalLayout_2.setContentsMargins(235, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.powerButton = QtWidgets.QPushButton(parent=self.headWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\PythonProjects\\AudioPlayer\\src\\client\\icons\\white\\power.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.powerButton.setIcon(icon5)
        self.powerButton.setIconSize(QtCore.QSize(20, 20))
        self.powerButton.setObjectName("powerButton")
        self.horizontalLayout_2.addWidget(self.powerButton)
        self.collapseButton = QtWidgets.QPushButton(parent=self.headWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\\PythonProjects\\AudioPlayer\\src\\client\\icons\\white\\minus-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.collapseButton.setIcon(icon6)
        self.collapseButton.setIconSize(QtCore.QSize(20, 20))
        self.collapseButton.setFlat(True)
        self.collapseButton.setObjectName("collapseButton")
        self.horizontalLayout_2.addWidget(self.collapseButton)
        self.closeButton = QtWidgets.QPushButton(parent=self.headWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:\\PythonProjects\\AudioPlayer\\src\\client\\icons\\white\\x-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeButton.setIcon(icon7)
        self.closeButton.setIconSize(QtCore.QSize(20, 20))
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
